from tkinter import *
root = Tk()
root.title('login app')
root.geometry('400x400')
frame = Frame(master=root, height = 200, width = 360, bg = '#d0efff')
IbI1 = Label(frame, text = 'Full name', bg = '#3859D3', fg = 'white', width = 12)
IbI2 = Label(frame, text = 'Email Id', bg = '#3859D3', fg = 'white', width = 12)
IbI3 = Label(frame, text = 'Enter Password', bg = '#3859D3', fg = 'white', width = 12)
name_entry = Entry(frame)
email_entry = Entry(frame)
pass_entry = Entry(frame, show ='*')
def display():
    name = name_entry.get()
    greet = 'Hey'+name
    message = '\n congratulations on your new account!'
    textbox.insert(END, greet)
    textbox.insert(END, message)
textbox = Text(bg = '#BEBEBE', fg = 'black')
btn = Button(text = 'create account', command=display, bg = 'red')
frame.place(x=20,y=20)
IbI1.place(x=20,y=20)
name_entry.place(x=150,y=20)
IbI2.place(x=20,y=80)
email_entry.place(x=150,y=80)
IbI3.place(x=20,y=140)
pass_entry.place(x=150,y=140)
btn.place(x=130,y=210)
textbox.place(y=250)
root.mainloop()